# Generated by Django 3.0.2 on 2020-01-04 09:00

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChairMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя', max_length=200, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Введите фамилию', max_length=200, verbose_name='Фамилия')),
                ('middle_name', models.CharField(help_text='Введите отчество', max_length=200, verbose_name='Отчество')),
            ],
            options={
                'verbose_name_plural': 'Председатели',
            },
        ),
        migrations.CreateModel(
            name='ElectricMeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricMeterReadings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LandPlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Snt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите полное название вашего СНТ', max_length=200, verbose_name='Наименование СНТ')),
                ('personal_acc', models.CharField(help_text='Введите номер расчетного счета (20-и значное число)', max_length=20, validators=[data.models.validate_chars, data.models.validate_20_length], verbose_name='Номер расчетного счета')),
                ('bank_name', models.CharField(help_text='Введите наименование банка получателя', max_length=45, verbose_name='Наименование банка получателя')),
                ('bic', models.CharField(help_text='Введите БИК (9-и значное число)', max_length=9, validators=[data.models.validate_chars, data.models.validate_9_length], verbose_name='БИК')),
                ('corresp_acc', models.CharField(help_text='Введите номер кор./счета (20-и значное число)', max_length=20, validators=[data.models.validate_chars, data.models.validate_20_length], verbose_name='Номер кор./счета')),
                ('inn', models.CharField(help_text='Введите ИНН (10-и значное число)', max_length=10, validators=[data.models.validate_chars, data.models.validate_10_length], verbose_name='ИНН')),
                ('kpp', models.CharField(help_text='Введите КПП (9-и значное число)', max_length=9, validators=[data.models.validate_chars, data.models.validate_9_length], verbose_name='КПП')),
            ],
            options={
                'verbose_name_plural': 'СНТ',
            },
        ),
        migrations.CreateModel(
            name='Tarrifs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
