# Generated by Django 3.0.2 on 2020-01-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChairMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricMeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricMeterReadings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LandPlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Snt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите полное название вашего СНТ', max_length=200, verbose_name='Наименование СНТ')),
                ('personal_acc', models.CharField(help_text='Введите номер расчетного счета', max_length=20, verbose_name='Номер расчетного счета')),
                ('bank_name', models.CharField(help_text='Введите наименование банка получателя', max_length=45, verbose_name='Наименование банка получателя')),
                ('bic', models.CharField(help_text='Введите БИК', max_length=9, verbose_name='БИК')),
                ('corresp_acc', models.CharField(help_text='Введите номер кор./счета', max_length=20, verbose_name='Номер кор./счета')),
                ('inn', models.CharField(help_text='Введите номер ИНН', max_length=10, verbose_name='ИНН')),
                ('kpp', models.CharField(help_text='Введите номер КПП', max_length=9, verbose_name='КПП')),
            ],
            options={
                'verbose_name_plural': 'СНТ',
            },
        ),
        migrations.CreateModel(
            name='Tarrifs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
