# Generated by Django 3.0.2 on 2020-01-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricmeterreadings',
            name='record_date',
            field=models.DateField(auto_now_add=True, help_text='Дата снятия показаний счетчика', verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='electricmeterreadings',
            name='record_status',
            field=models.CharField(choices=[('n', 'Новые показания'), ('p', 'Оплачено'), ('c', 'Оплата подтверждена'), ('o', 'Оплачено ранее')], default='n', help_text='Статус показаний', max_length=1, verbose_name='Статус'),
        ),
    ]
