# Generated by Django 3.0.2 on 2020-01-06 14:11

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairman',
            name='first_name',
            field=models.CharField(help_text='Введите имя', max_length=200, validators=[data.models.validate_human_names], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='chairman',
            name='last_name',
            field=models.CharField(help_text='Введите фамилию', max_length=200, validators=[data.models.validate_human_names], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='chairman',
            name='middle_name',
            field=models.CharField(help_text='Введите отчество', max_length=200, validators=[data.models.validate_human_names], verbose_name='Отчество'),
        ),
    ]
