# Generated by Django 3.0.2 on 2020-01-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='end_owner_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата окончания владения'),
        ),
    ]
