# Generated by Django 3.0.2 on 2020-01-03 16:57

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snt',
            name='personal_acc',
            field=models.CharField(help_text='Введите номер расчетного счета', max_length=20, validators=[data.models.validate_account_number], verbose_name='Номер расчетного счета'),
        ),
    ]
