# Generated by Django 3.0.2 on 2020-03-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricalcounter',
            name='t_single',
        ),
    ]
