# Generated by Django 3.0.2 on 2020-01-04 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chairman',
            options={'verbose_name': 'председатель', 'verbose_name_plural': 'председатели'},
        ),
    ]
