# Generated by Django 3.0.2 on 2020-01-03 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snt',
            options={'verbose_name_plural': 'СНТ'},
        ),
    ]
