# Generated by Django 3.0.2 on 2020-02-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='electricitypayments',
            unique_together=set(),
        ),
    ]
