# Generated by Django 3.0.2 on 2020-03-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_electricalcounter_t_single'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricalcounter',
            name='t_single',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Однотарифный', null=True, verbose_name='Показание при установке/приемке'),
        ),
    ]
