# Generated by Django 3.0.2 on 2020-01-06 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200106_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snt',
            options={'verbose_name': 'СНТ', 'verbose_name_plural': 'СНТ'},
        ),
    ]
