# Generated by Django 3.0.2 on 2020-01-03 17:48

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200103_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snt',
            name='personal_acc',
            field=models.CharField(help_text='Введите номер расчетного счета (20-и значное число)', max_length=20, validators=[data.models.validate_account_number], verbose_name='Номер расчетного счета'),
        ),
    ]
