# Generated by Django 3.0.2 on 2020-01-06 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200106_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='snt',
            name='chair_man',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='data.ChairMan'),
        ),
    ]
