# Generated by Django 3.0.2 on 2020-01-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200103_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snt',
            options={'verbose_name_plural': 'СНТs'},
        ),
    ]
