# Generated by Django 3.0.2 on 2020-01-06 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_snt_chair_man'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snt',
            name='chair_man',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.ChairMan'),
        ),
    ]
