# Generated by Django 3.0.2 on 2020-01-06 18:40

import data.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200106_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='landplot',
            name='owner',
            field=models.ForeignKey(help_text='Владелец участка', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Owner', verbose_name='владелец участка'),
        ),
        migrations.AddField(
            model_name='landplot',
            name='snt',
            field=models.ForeignKey(help_text='СНТ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Snt', verbose_name='СНТ'),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='plot_area',
            field=models.DecimalField(decimal_places=2, help_text='Площадь участка (кв.м)', max_digits=7, verbose_name='Площадь участка'),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='plot_number',
            field=models.CharField(help_text='Номер участка', max_length=10, unique=True, verbose_name='Номер участка'),
        ),
        migrations.AlterField(
            model_name='snt',
            name='bank_name',
            field=models.CharField(help_text='Наименование банка получателя', max_length=45, verbose_name='Наименование банка получателя'),
        ),
        migrations.AlterField(
            model_name='snt',
            name='bic',
            field=models.CharField(help_text='БИК (9-и значное число)', max_length=9, validators=[data.models.validate_number, data.models.validate_9_length], verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='snt',
            name='corresp_acc',
            field=models.CharField(help_text='Номер кор./счета (20-и значное число)', max_length=20, validators=[data.models.validate_number, data.models.validate_20_length], verbose_name='Номер кор./счета'),
        ),
        migrations.AlterField(
            model_name='snt',
            name='inn',
            field=models.CharField(help_text='ИНН (10-и значное число)', max_length=10, validators=[data.models.validate_number, data.models.validate_10_length], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='snt',
            name='kpp',
            field=models.CharField(help_text='КПП (9-и значное число)', max_length=9, validators=[data.models.validate_number, data.models.validate_9_length], verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='snt',
            name='name',
            field=models.CharField(help_text='Полное название СНТ', max_length=200, verbose_name='Наименование СНТ'),
        ),
        migrations.AlterField(
            model_name='snt',
            name='personal_acc',
            field=models.CharField(help_text='Номер расчетного счета (20-и значное число)', max_length=20, validators=[data.models.validate_number, data.models.validate_20_length], verbose_name='Номер расчетного счета'),
        ),
    ]
