# Generated by Django 3.0.2 on 2020-01-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200103_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snt',
            options={'verbose_name_plural': 'СНТ'},
        ),
        migrations.AlterField(
            model_name='snt',
            name='name',
            field=models.CharField(help_text='Введите полное название вашего СНТ', max_length=200, verbose_name='Название СНТ'),
        ),
    ]
