# Generated by Django 3.0.2 on 2020-01-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20200123_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitypayments',
            name='record_status',
            field=models.CharField(choices=[('n', 'Новые показания'), ('p', 'Оплачено'), ('c', 'Оплата подтверждена'), ('i', 'Первые показания')], default='n', help_text='Статус показаний', max_length=1, verbose_name='Статус'),
        ),
    ]
