# Generated by Django 3.0.2 on 2020-01-06 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20200106_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snt',
            name='chair_man',
            field=models.OneToOneField(help_text='председатель садоводства', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.ChairMan', verbose_name='председатель'),
        ),
    ]
