# Generated by Django 3.0.2 on 2020-01-06 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20200106_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricMeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(help_text='Модель прибора учета электроэнергии', max_length=50, verbose_name='Модель')),
                ('serial_number', models.CharField(help_text='Серийный номер прибора учета электроэнергии', max_length=50, verbose_name='Серийный номер')),
                ('model_type', models.CharField(choices=[('1T', 'Однотарифный'), ('2T', 'Двухтарифный')], default='1T', help_text='Тип прибора учета', max_length=2, verbose_name='Тип')),
                ('acceptance_date', models.DateField(blank=True, default='unknown', null=True, verbose_name='дата установки')),
            ],
            options={
                'verbose_name': 'прибор учета электроэнергии',
                'verbose_name_plural': 'приборы учета электроэнергии',
            },
        ),
        migrations.AlterField(
            model_name='landplot',
            name='snt',
            field=models.ForeignKey(help_text='Расположен в СНТ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Snt', verbose_name='СНТ'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='status',
            field=models.CharField(choices=[('c', 'Настоящий'), ('p', 'Прежний')], default='c', help_text='Статус владельца', max_length=1, verbose_name='Статус владельца'),
        ),
    ]
