# Generated by Django 3.0.2 on 2020-01-06 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20200106_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='landplot',
            name='electric_meter',
            field=models.OneToOneField(help_text='Прибор учета электроэнергии', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.ElectricMeter', verbose_name='Счетчик'),
        ),
        migrations.AlterField(
            model_name='electricmeter',
            name='acceptance_date',
            field=models.DateField(blank=True, default='Неизвестна', null=True, verbose_name='дата установки'),
        ),
        migrations.AlterField(
            model_name='electricmeter',
            name='model_type',
            field=models.CharField(choices=[('T1', 'Однотарифный'), ('T2', 'Двухтарифный')], default='T1', help_text='Тип прибора учета', max_length=2, verbose_name='Тип'),
        ),
    ]
