# Generated by Django 3.0.2 on 2020-02-06 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0006_landplot_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landplot',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Аккаунт пользователя на сайте', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Логин'),
        ),
    ]
