# Generated by Django 3.0.2 on 2020-01-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20200106_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricmeter',
            name='acceptance_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата установки'),
        ),
    ]
