# Generated by Django 3.0.2 on 2020-02-14 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20200206_1230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElectricMeter',
            new_name='ElectricalCounter',
        ),
        migrations.RenameField(
            model_name='landplot',
            old_name='electric_meter',
            new_name='electrical_counter',
        ),
    ]
