# Generated by Django 3.0.2 on 2020-01-07 09:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20200106_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricMeterReadings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(default=datetime.date(2020, 1, 7), help_text='Дата снятия показаний счетчика', verbose_name='Дата')),
                ('t1_record', models.PositiveIntegerField(help_text='Показания T1 (6:00-23:00)', verbose_name='Тариф день')),
                ('t2_record', models.PositiveIntegerField(help_text='Показания Т2 (23:00-6:00)', verbose_name='Тариф ночь')),
                ('record_status', models.CharField(choices=[('new-pay-calc', 'Новые показания'), ('new-pay-bank', 'Оплачено через банк'), ('new-pay-conf', 'Последняя оплата'), ('old-pay-conf', 'Оплачено ранее')], default='new-pay-calc', help_text='Статус показаний', max_length=12, verbose_name='Статус')),
                ('plot_number', models.ForeignKey(help_text='Номер участка', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.LandPlot', verbose_name='Номер участка')),
            ],
        ),
    ]
