# Generated by Django 3.0.2 on 2020-01-07 10:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_electricmeterreadings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricmeterreadings',
            name='record_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 7, 10, 0, 31, 9267, tzinfo=utc), help_text='Дата снятия показаний счетчика', verbose_name='Дата'),
        ),
    ]
