# Generated by Django 3.0.2 on 2020-01-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20200107_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricmeterreadings',
            options={'verbose_name': 'показание счетчика', 'verbose_name_plural': 'показания счетчика'},
        ),
        migrations.AlterField(
            model_name='electricmeterreadings',
            name='record_date',
            field=models.DateField(auto_now_add=True, help_text='Дата снятия показаний счетчика', verbose_name='Дата'),
        ),
    ]
