# Generated by Django 3.0.2 on 2020-01-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20200107_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricmeterreadings',
            options={'verbose_name': 'данные показаний счетчика', 'verbose_name_plural': 'показания счетчика'},
        ),
        migrations.AlterField(
            model_name='electricmeterreadings',
            name='record_status',
            field=models.CharField(choices=[('new-pay-calc', 'Новые показания'), ('new-pay-bank', 'Оплачено через банк'), ('new-pay-conf', 'Последняя оплата'), ('old-pay-conf', 'Оплачено ранее')], default='new-pay-calc', help_text='Статус показаний', max_length=12, unique_for_date=models.DateField(auto_now_add=True, help_text='Дата снятия показаний счетчика', verbose_name='Дата'), verbose_name='Статус'),
        ),
    ]
