# Generated by Django 3.0.2 on 2020-01-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20200107_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricmeterreadings',
            name='record_status',
            field=models.CharField(choices=[('new-pay-calc', 'Новые показания'), ('new-pay-bank', 'Оплачено через банк'), ('new-pay-conf', 'Последняя оплата'), ('old-pay-conf', 'Оплачено ранее')], default='new-pay-calc', help_text='Статус показаний', max_length=12, unique_for_date='record_date', verbose_name='Статус'),
        ),
    ]
