# Generated by Django 3.0.2 on 2020-01-07 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20200107_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricmeterreadings',
            name='plot_number',
            field=models.ForeignKey(help_text='Номер участка', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.LandPlot', unique_for_date='record_date', verbose_name='Номер участка'),
        ),
        migrations.AlterField(
            model_name='electricmeterreadings',
            name='record_status',
            field=models.CharField(choices=[('new-pay-calc', 'Новые показания'), ('new-pay-bank', 'Оплачено через банк'), ('new-pay-conf', 'Последняя оплата'), ('old-pay-conf', 'Оплачено ранее')], default='new-pay-calc', help_text='Статус показаний', max_length=12, verbose_name='Статус'),
        ),
    ]
