# Generated by Django 3.0.2 on 2020-01-07 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20200107_1333'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='electricmeterreadings',
            unique_together={('record_date', 'plot_number')},
        ),
    ]
