# Generated by Django 3.0.2 on 2020-01-07 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20200107_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landplot',
            name='electric_meter',
            field=models.OneToOneField(help_text='Данные прибора учета электроэнергии', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.ElectricMeter', verbose_name='Счетчик'),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='plot_area',
            field=models.DecimalField(decimal_places=2, help_text='Единица измерения кв.м', max_digits=7, verbose_name='Размер участка'),
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_date', models.DateField(help_text='Дата введения/изменения тарифа', verbose_name='Дата')),
                ('t1_rate', models.DecimalField(decimal_places=2, help_text='Тариф Т1 (6:00-23:00)', max_digits=5, verbose_name='Тариф день')),
                ('t2_rate', models.DecimalField(decimal_places=2, help_text='Тариф Т2 (23:00-6:00)', max_digits=5, verbose_name='Тариф ночь')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'unique_together': {('intro_date', 't1_rate', 't2_rate')},
            },
        ),
    ]
