# Generated by Django 3.0.2 on 2020-01-14 05:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20200107_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricmeterreadings',
            name='t1_record',
        ),
        migrations.RemoveField(
            model_name='electricmeterreadings',
            name='t2_record',
        ),
        migrations.AddField(
            model_name='electricmeterreadings',
            name='pay_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата оплаты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electricmeterreadings',
            name='sum_tot',
            field=models.FloatField(default=0, help_text='Общая сумма к оплате', verbose_name='Итог'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electricmeterreadings',
            name='t1_amount',
            field=models.FloatField(default=0, help_text='Сумма по тарифу Т1', verbose_name='Сумма (день)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electricmeterreadings',
            name='t1_cons',
            field=models.PositiveIntegerField(default=0, verbose_name='Потрачено квт/ч (день)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electricmeterreadings',
            name='t1_new',
            field=models.PositiveIntegerField(default=0, help_text='Тариф T1 (6:00-23:00)', verbose_name='Текущее показание (день)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electricmeterreadings',
            name='t1_prev',
            field=models.PositiveIntegerField(default=0, help_text='Тариф Т1 (6:00-23:00)', verbose_name='Предыдущее показание (день)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electricmeterreadings',
            name='t2_amount',
            field=models.FloatField(default=0, help_text='Сумма по тарифу Т2', verbose_name='Сумма (ночь)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electricmeterreadings',
            name='t2_cons',
            field=models.PositiveIntegerField(default=0, verbose_name='Потрачено квт/ч (ночь)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electricmeterreadings',
            name='t2_new',
            field=models.PositiveIntegerField(default=0, help_text='Тариф Т2 (23:00-6:00)', verbose_name='Текущее показание (ночь)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electricmeterreadings',
            name='t2_prev',
            field=models.PositiveIntegerField(default=0, help_text='Тариф Т2 (23:00-6:00)', verbose_name='Предыдущее показание (ночь)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='electricmeterreadings',
            name='record_status',
            field=models.CharField(choices=[('n', 'Новые показания'), ('p', 'Оплачено через банк'), ('c', 'Последняя оплата'), ('o', 'Оплачено ранее')], default='n', help_text='Статус показаний', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='plot_area',
            field=models.FloatField(help_text='Единица измерения кв.м', verbose_name='Размер участка'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='t1_rate',
            field=models.FloatField(help_text='Тариф Т1 (6:00-23:00)', verbose_name='Электроэнергия день'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='t2_rate',
            field=models.FloatField(help_text='Тариф Т2 (23:00-6:00)', verbose_name='Электроэнергия ночь'),
        ),
    ]
