# Generated by Django 3.0.2 on 2020-01-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20200114_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricmeterreadings',
            name='sum_tot',
            field=models.FloatField(blank=True, help_text='Общая сумма к оплате', verbose_name='Итог'),
        ),
        migrations.AlterField(
            model_name='electricmeterreadings',
            name='t1_amount',
            field=models.FloatField(blank=True, help_text='Сумма по тарифу Т1', verbose_name='Сумма (день)'),
        ),
        migrations.AlterField(
            model_name='electricmeterreadings',
            name='t1_cons',
            field=models.PositiveIntegerField(blank=True, verbose_name='Потрачено квт/ч (день)'),
        ),
        migrations.AlterField(
            model_name='electricmeterreadings',
            name='t1_prev',
            field=models.PositiveIntegerField(blank=True, help_text='Тариф Т1 (6:00-23:00)', verbose_name='Предыдущее показание (день)'),
        ),
        migrations.AlterField(
            model_name='electricmeterreadings',
            name='t2_amount',
            field=models.FloatField(blank=True, help_text='Сумма по тарифу Т2', verbose_name='Сумма (ночь)'),
        ),
        migrations.AlterField(
            model_name='electricmeterreadings',
            name='t2_cons',
            field=models.PositiveIntegerField(blank=True, verbose_name='Потрачено квт/ч (ночь)'),
        ),
        migrations.AlterField(
            model_name='electricmeterreadings',
            name='t2_prev',
            field=models.PositiveIntegerField(blank=True, help_text='Тариф Т2 (23:00-6:00)', verbose_name='Предыдущее показание (ночь)'),
        ),
    ]
