# Generated by Django 3.0.2 on 2020-01-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_auto_20200115_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricmeterreadings',
            name='record_date',
            field=models.DateField(help_text='Дата снятия показаний счетчика', verbose_name='Дата'),
        ),
    ]
