# Generated by Django 3.0.2 on 2020-01-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_auto_20200115_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricmeterreadings',
            name='pay_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
    ]
