# Generated by Django 3.0.2 on 2020-01-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_auto_20200115_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricmeterreadings',
            name='sum_tot',
            field=models.FloatField(default=None, help_text='Общая сумма к оплате', null=True, verbose_name='Итог'),
        ),
        migrations.AlterField(
            model_name='electricmeterreadings',
            name='t1_amount',
            field=models.FloatField(default=None, help_text='Сумма по тарифу Т1', null=True, verbose_name='Сумма (день)'),
        ),
        migrations.AlterField(
            model_name='electricmeterreadings',
            name='t1_cons',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Потрачено квт/ч (день)'),
        ),
        migrations.AlterField(
            model_name='electricmeterreadings',
            name='t1_prev',
            field=models.PositiveIntegerField(default=None, help_text='Тариф Т1 (6:00-23:00)', null=True, verbose_name='Предыдущее показание (день)'),
        ),
        migrations.AlterField(
            model_name='electricmeterreadings',
            name='t2_amount',
            field=models.FloatField(default=None, help_text='Сумма по тарифу Т2', null=True, verbose_name='Сумма (ночь)'),
        ),
        migrations.AlterField(
            model_name='electricmeterreadings',
            name='t2_cons',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Потрачено квт/ч (ночь)'),
        ),
        migrations.AlterField(
            model_name='electricmeterreadings',
            name='t2_new',
            field=models.PositiveIntegerField(default=None, help_text='Тариф Т2 (23:00-6:00)', null=True, verbose_name='Текущее показание (ночь)'),
        ),
        migrations.AlterField(
            model_name='electricmeterreadings',
            name='t2_prev',
            field=models.PositiveIntegerField(default=None, help_text='Тариф Т2 (23:00-6:00)', null=True, verbose_name='Предыдущее показание (ночь)'),
        ),
    ]
