# Generated by Django 3.0.2 on 2020-01-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_auto_20200116_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='rate_status',
            field=models.CharField(choices=[('c', 'Действущий')], default='c', max_length=1, null=True, unique=True, verbose_name='Вид тарифа'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='intro_date',
            field=models.DateField(auto_now_add=True, help_text='Дата введения/изменения тарифа', verbose_name='Дата'),
        ),
    ]
