# Generated by Django 3.0.2 on 2020-01-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_auto_20200116_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate_status',
            field=models.CharField(blank=True, choices=[('c', 'Действущий')], default='c', max_length=1, null=True, unique=True, verbose_name='Вид тарифа'),
        ),
    ]
