# Generated by Django 3.0.2 on 2020-01-16 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_auto_20200116_1442'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('intro_date', 'rate_status')},
        ),
    ]
