# Generated by Django 3.0.2 on 2020-01-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_auto_20200116_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricmeterreadings',
            name='sum_tot',
            field=models.DecimalField(decimal_places=2, default=None, help_text='Общая сумма к оплате', max_digits=7, null=True, verbose_name='Итог'),
        ),
        migrations.AlterField(
            model_name='electricmeterreadings',
            name='t1_amount',
            field=models.DecimalField(decimal_places=2, default=None, help_text='Сумма по тарифу Т1', max_digits=7, null=True, verbose_name='Сумма (день)'),
        ),
        migrations.AlterField(
            model_name='electricmeterreadings',
            name='t2_amount',
            field=models.DecimalField(decimal_places=2, default=None, help_text='Сумма по тарифу Т2', max_digits=7, null=True, verbose_name='Сумма (ночь)'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='t1_rate',
            field=models.DecimalField(decimal_places=2, help_text='Тариф Т1 (6:00-23:00)', max_digits=4, verbose_name='Электроэнергия день'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='t2_rate',
            field=models.DecimalField(decimal_places=2, help_text='Тариф Т2 (23:00-6:00)', max_digits=4, verbose_name='Электроэнергия ночь'),
        ),
    ]
